#!/bin/bash
rm -r $MODELSIM_LIBS/lib_nanoproc_bench
vlib $MODELSIM_LIBS/lib_nanoproc_bench

vcom -work lib_nanoproc_bench bench_system.vhd
if [ "$?" != 0 ]
then exit -1
fi

vcom -work lib_nanoproc_bench cfg_bench_system.vhd
if [ "$?" != 0 ]
then exit -1
fi

